def Weird_News():
    print("This is the Weird News Madlibs.")
    noun1 = input("Enter a noun: \n")
    wacky_state = input("Enter a wacky state: \n")
    verb1 = input("Enter a verb: \n")
    noun2 = input("Enter a noun: \n")
    proper_name = input("Enter a proper noun: \n")
    verb2 = input("Enter a verb: \n")
    noun3 = input("Enter a noun: \n")
    verb3 = input("Enter a verb: \n")
    noun4 = input("Enter a noun: \n")
    body_part = input("Enter a part of the body: \n")
    adjective1 = input("Enter an adjective: \n")
    relative = input("Enter a relative: \n")
    activity = input("Enter an activity: \n")
    chain_restaurant = input("Enter a chain restaurant: \n")
    adjective2 = input("Enter an adjective in past tense: \n")
    month = input("Enter a month: \n")
    verb4 = input("Enter a verb: \n")
    noun5 = input("Enter a noun: \n")
    verb5 = input("Enter a verb in past tense: \n")
    adjective3 = input("Enter an adjective: \n")
    verb6 = input("Enter a verb: \n")
    noun6 = input("Enter a noun: \n")
    print("You are almost done one more")
    noun7 = input("Enter a plural noun: \n")
    print("Now I will printing the story \n")
    print("A",noun1,"in",wacky_state,"was arrested this morning after he",verb1,"a \n in front of",noun2,".",proper_name,", had a history of",verb2,", but \n no one-not even his",noun3,"-ever imagined he'd",verb3,"with a",noun4,"\n stuck in his",body_part,".\n \n I always thought he was",adjective1,", but I never thought he'd do something \n like this. Even his",relative, "was surprised. \n \n After a brief",activity,", cops followed him to a", chain_restaurant,", where he re reportedly \n",adjective2,"in the frying machine. \n \n In",month,", a women was charged with a similar crime. But rather than \n", verb4,"with a",noun5,", she",verb5,"with a",adjective3,"\n dog \n \n Either way, we imagined that after witnessing him",verb6,"with a",noun6,"there \n are probably a whole lot of", noun7,"that are gonna need some therapy.")
    Menu()

def Trip_Park():
    print("This is the Trip to the Park")
    person = input("Enter a person: \n")
    adjective1 = input("Enter an adjective: \n")
    adjective2 = input("Enter an adjective: \n")
    noun1 = input("Enter a noun: \n")
    adjective3 = input("Enter an adjective: \n")
    noun2 = input("Enter a noun: \n")
    adjective4 = input("Enter an adjective: \n")
    adjective5 = input("Enter an adjective: \n")
    verb1 = input("Enter a verb: \n")
    verb2 = input("Enter a verb: \n")
    person = input("Enter a person: \n")
    verb3 = input("Enter a verb: \n")
    adjective6 = input("Enter an adjective: \n")
    print("You are almost done enter one more \n")
    verb4 = input("Enter a verb: \n")
    print("Now I will print the story \n")
    print("Yesterday,",person,"and I went to the park. On our way \n to the",adjective1,"park, we saw a", adjective2, noun1,"\n on a bike. We also saw big",adjective3, "balloons tied \n to a", noun2,". Once we got to the",adjective4,"\n park, the sky turned",adjective5,". It started to",verb1," and \n",verb2,".",person, "and I", verb3,"all the way home. \n Tomorrow, we will try to go to the",adjective6,"park again and \n hope it doesn't",verb4,".") 
    Menu()    

def Bedtime_Story():

    print("This is the World's Worst Bedtime Story")
    place1 = input("Enter a place: \n")
    adjective1 = input("Enter an adjective: \n")
    celeb1 = input("Enter a female celebrity: \n")
    body_part1 = input("Enter a body part: \n")
    body_part2 = input("Enter a body part: \n")
    organ = input("Enter a human organ: \n")
    adjective2 = input("Enter an adjective: \n")
    celeb2 = input("Enter a male celebrity: \n")
    adjective3 = input("Enter an adjective: \n")
    body_part3 = input("Enter a body part: \n")
    body_part4 = input("Enter a body part: \n")
    place2 = input("Enter a place: \n")
    celeb3 = input("Enter a celebrity: \n")
    animal = input("Enter an animal: \n")
    verb1 = input("Enter a verb: \n")
    number = int(input("Enter an integer"))
    body_part5 = input("Enter a body part: \n")
    adjective4 = input("Enter an adjective: \n")
    adjective5 = input("Enter an adjective: \n")
    print("You are almost done enter one more: /n")
    verb2 = input("Enter a verb in past tense: \n")
    print("Now I will print the story \n")
    print("Once upon a time, in a place called",place1,", there was \n a",adjective1,"princess named", celeb1,". Her kingdom \n was huge, but her",body_part1,"was bigger. She was beautiful \n from her",body_part2,"to her", organ,". One day she saw a \n",adjective2,"prince named",celeb2,"He had a \n", adjective3,"face. As soon as his", body_part3,"touched her \n",body_part4,"they fell in love. They got married at",place2,"the following day. \n \n Not long after, they had a baby. They decided to call him/her \n",celeb3,". He/She looked like a",animal,"He/She \n used to",verb1,number,"times a day so that his/her \n", body_part5,"would be",adjective4,"and",adjective5,". \n And they",verb2,"happily ever after!")
    Menu()
def Goodbye():
    print("Thanks for playing, goodbye")
def Menu():
    exit = input("Do you want to quit the game: \n Yes/No: \n ")
    if exit != "Yes":
        story = input("Select a story to play \n (Weird News/Trip to the Park/The World's Worst Bedtime Story): \n")
        if story == "Weird News":
            Weird_News()
        elif story == "Trip to the Park":
            Trip_Park()
        elif story == "The World's Worst Bedtime Story":
            Bedtime_Story()
        else:
            print("That is an invalid input")
            Menu()
        if exit == "Yes":
            Goodbye()
def Instructions():
    print("To play: Enter a word based on what the computer asks you, and watch as the computer turns those words into a funny story")
    Beginning()
def Beginning():
    print("Welcome to madlibs, the word game")
    location = input("Do you want to learn the instructions or go to the instruction menu (Menu/Instructions): \n")
    if location == 'Menu':
        Menu()
    elif location == 'Instructions':
        Instructions()
Beginning()
